### ISSUE TITLE
CSS 三栏布局（两侧固定，中间自适应）方案整理

### ISSUE THREAD

**Issue by LiuXiaowenn** [LiuXiaowenn/blog#10]
初始效果:

![image](https://user-images.githubusercontent.com/25410850/44772095-88519d80-ab9f-11e8-917e-63bf92f48576.png)

html:

```html
<div class="wrap">
  <div class="left">左侧</div>
  <div class="middle">中间</div>
  <div class="right">右侧</div>
</div>
```

css:

```css
.wrap {
  background: #ddd;
  padding: 10px;
}  
.left {
  background: coral;
  width: 150px;
  height: 150px;
}
.right {
  background: lightblue;
  width: 100px;
  height: 100px;
}
.middle {
  background: lightpink;
}
```

--------

以下方案中间的内容必须放在 HTML 结构的最后，否则右侧会沉在中间内容的下侧：

效果：
![image](https://user-images.githubusercontent.com/25410850/44772455-7b817980-aba0-11e8-8231-74419b9a829c.png)

html：
```html
<div class="wrap">
  <div class="left">左侧</div>
  <div class="middle">中间</div>
  <div class="right">右侧</div>
</div>
```

1. 流体布局

```css
.left {
  float: left;
}
.right {
  float: right;
}
.middle {
  margin-left: 160px; /* 大于左侧宽度 */
  margin-right: 110px; /* 大于右侧宽度 */
}
```

2. BFC 三栏布局

```css
.wrap {
  overflow: hidden;  /* 清除浮动 */
}
.left {
  float: left;
  margin-right: 10px;
}
.right {
  float: right;
  margin-left: 10px;
}
.middle {
  overflow: hidden; /* 触发 BFC，不会与浮动元素重叠 */
}
```

---------------

双飞翼布局：

效果：

![image](https://user-images.githubusercontent.com/25410850/44773992-8d651b80-aba4-11e8-9dc2-f07386d5c526.png)

```html
<div class="wrap">
    <div class="middle">
        <div class="content">中间</div>
    </div>
    <div class="left">左侧</div>
    <div class="right">右侧</div>
</div>
```

```css
.wrap {
  overflow: hidden;  /* 清除浮动 */
}
.middle {
  float: left;
  width: 100%;
}
.content {
  margin-left: 160px;
  margin-right: 110px;
}
.left {
  float: left;
  margin-left: -100%;
}
.right {
  float: right;
  margin-left: -100px; /* 绝对值应大于等于自身宽度 */
}
```

---------------

flex 布局：

效果：

![image](https://user-images.githubusercontent.com/25410850/44774428-aa4e1e80-aba5-11e8-9e14-ea50eb8568e7.png)

```html
<div class="wrap">
    <div class="left">左侧</div>
    <div class="middle">中间</div>
    <div class="right">右侧</div>
</div>
```

```css
.wrap {
  display: flex;
}

.middle {
  flex: 1;
  margin-left: 10px;
  margin-right: 10px;
}
```
**参考链接**:
- [CSS || 三栏布局，两边固定，中间自适应](https://segmentfault.com/a/1190000008705541)
- [详解 CSS 七种三栏布局技巧](https://zhuanlan.zhihu.com/p/25070186)
