### ISSUE TITLE
使用 CSS Animation 实现旋转的 loading

### ISSUE THREAD

**Issue by LiuXiaowenn** [LiuXiaowenn/blog#8]
实现效果:
<div align="center"><img src="https://user-images.githubusercontent.com/25410850/44705981-bd43ee80-aad2-11e8-8cff-dca00698f6a2.gif" /></div>

思路:
<div align="center"><img src="https://user-images.githubusercontent.com/25410850/44706260-9df99100-aad3-11e8-8a5a-9976a593164e.png" width="200px" /></div>

html:
```html
<div class="container">
  <div class="bubble"></div>
  <div class="bubble"></div>
  <div class="bubble"></div>
  <div class="bubble"></div>
</div>
<div class="container">
  <div class="bubble"></div>
  <div class="bubble"></div>
  <div class="bubble"></div>
  <div class="bubble"></div>
</div>
```

css:
```css
body {
  background-color: lightblue;
  position: relatve;
}

.container {
  width: 50px;
  height: 50px;
  /* 垂直居中 */
  top: 50%;
  left: 50%;
  margin: -25px 0 0 -25px;
  position: absolute;
  .bubble {
    width: 10px;
    height: 10px;
    border-radius: 50%;
    background-color: #fff;
    position: absolute;
    /* 设置动画 */
    animation-name: bubble;
    animation-duration: 1s;
    animation-iteration-count: infinite;
    &:nth-child(1) {
      top: -5px;
      left: -5px;
    }
    &:nth-child(2) {
      top: -5px;
      right: -5px;
    }
    &:nth-child(3) {
      bottom: -5px;
      right: -5px;
    }
    &:nth-child(4) {
      bottom: -5px;
      left: -5px;
    }
  }
  &:nth-child(1) {
    transform: rotate(45deg);
    .bubble:nth-child(1) { animation-delay: 0.125s;}
    .bubble:nth-child(2) { animation-delay: 0.375s;}
    .bubble:nth-child(3) { animation-delay: 0.5s;}
    .bubble:nth-child(4) { animation-delay: 0.75s;}
  }
  &:nth-child(2) {
    .bubble:nth-child(2) { animation-delay: 0.25s;}
    .bubble:nth-child(3) { animation-delay: 0.375s;}
    .bubble:nth-child(4) { animation-delay: 0.625s;}
    .bubble:nth-child(1) { animation-delay: 0.875s;}
  }
}

@keyframes bubble {
  0%, 100% {
    transform:scale(0);
  }
	50% {
    transform: scale(1);
  }
}

```
