### ISSUE TITLE
CSS 两列自适应布局方案整理

### ISSUE THREAD

**Issue by LiuXiaowenn** [LiuXiaowenn/blog#9]
## 两列自适应布局

-------------------
初始效果:
![image](https://user-images.githubusercontent.com/25410850/44718469-be851380-aaf2-11e8-92fe-6ec77589eab4.png)

html:
```html
<div class="parent">
  <div class="left">
    左边固定宽度，高度不固定</br> </br></br></br>高度有可能会很小，也可能很大
  </div>
  <div class="right">
    这里的内容可能比左侧高，也可能比左侧低，宽度需要自适应<br />
    基本的样式是，两个 div 相距20px, 左侧 div 宽 120px
  </div>
</div>
```

css:
```css
.parent {
  padding: 10px 10px;
  border: 5px solid #ddd;
}
.left {
  width: 120px;
  background-color: lightblue;
}
.right {
  margin-left: 20px;
  background-color: lightgreen;
}
```
----------------

1. ``float`` + ``BFC``

> 缺点：两列不一定等高，由自身 ``height`` 决定

```css
.left{
  background-color: lightblue;
  float: left;
  width: 100px;  /* 左边可以不定宽，由内容决定宽度 */
}
.right{
  background-color: lightgreen;
  overflow: hidden;  /* 触发 BFC */
}
```

2. ``flex``

> 优点：两列完全等高
> 缺点：有兼容问题

```css
.parent {
  display: flex;
}
.left{
  background-color: lightblue;
  width: 100px;  /* 左边可以不定宽，由内容决定宽度 */
}
.right{
  background-color: lightgreen;
  flex: 1;
}
```
